branches:
  only:
  - master
  - stable
language: java
jdk:
- oraclejdk8
before_install:
install:
- mvn clean install -Dgpg.skip=true
before_script: 
script: 
after_success:
- mvn clean deploy  -Dgpg.skip=true
after_failure:
- cat com.github.lafa.common/target/surefire-reports/*.txt
- cat com.github.lafa.common/core/target/surefire-reports/*.txt
- cat com.github.lafa.common/core/target/surefire-reports/*.txt
